version: "3.8"
services:
  order-service:
    build: ./OrderService
    volumes:
      - ./OrderService:/app
      - order-data:/app/data
    depends_on:
    - rabbitmq
    ports:
      - ?

  payment-service:
    build: ./PaymentService
    volumes:
      - ./PaymentService:/app
      - payment-data:/app/data

  merchant-service:
    build: ./MerchantService
    volumes:
      - ./MerchantService:/app/merchant
      - merchant-data:/app/data
    ports:
      - ?

  inventory-service:
    build: ./InventoryService
    volumes:
      - ./InventoryService:/app/inventory
      - inventory-data:/app/data

  email-service:
    build: ./EmailService
    volumes:
      - ./EmailService:/app/email

  buyer-service:
    build: ./BuyerService
    volumes:
      - ./BuyerService:/app/buyer
      - buyer-data:/app/data
    ports:
      - ?

  rabbitmq:
    - rabbitmq-management
    ports:
      -

volumes:
  - order-data
  - payment-data
  - merchant-data
  - inventory-data
  - buyer-data