version: "3.8"
services:
  order-service:
    build: ./OrderService
    volumes:
      - ./OrderService:/app
    depends_on:
    - rabbitmq
    ports:
      - ?

  payment-service:
    build: ./PaymentService
    volumes:
      - ./PaymentService:/app

  merchant-service:
    build: ./MerchantService
    volumes:
      - ./MerchantService:/app/merchant
    ports:
      - ?

  inventory-service:
    build: ./InventoryService
    volumes:
      - ./InventoryService:/app/inventory

  email-service:
    build: ./EmailService
    volumes:
      - ./EmailService:/app/email

  buyer-service:
    build: ./BuyerService
    volumes:
      - ./BuyerService:/app/buyer
    ports:
      - ?

  rabbitmq:
    - rabbitmq-management
    ports:
      -

volumes:
  # TODO