version: "3.8"
services:
  order-service:
    build: ./OrderService
    volumes:
      - ./OrderService:/app/order
    depends_on:
    - rabbitmq

  payment-service:
    volumes:
      - ./PaymentService:/app/payment

  merchant-service:
    volumes:
      - ./MerchantService:/app/merchant

  inventory-service:
    volumes:
      - ./InventoryService:/app/inventory

  email-service:
    volumes:
      - ./EmailService:/app/email
    depends_on:
      - yagmail

  buyer-service:
    volumes:
      - ./BuyerService:/app/buyer

  rabbitmq:
    - rabbitmq-management
    ports:
      -

volumes:
  # TODO