version: "3.8"
services:
  message-api:
    build: ./MessageApi
    volumes:
      - ./MessageApi:/app/Api
    depends_on:
    - rabbitmq

  message-processsor:
    volumes:
      - ./MessageProcessor:/app/Processor

  rabbitmq:
    - rabbitmq-management
    ports:
      -

volumes:
  # TODO